//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLib_Client.VLibSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/JCDecaux_API")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommercialNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Cities {
            get {
                return this.CitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CitiesField, value) != true)) {
                    this.CitiesField = value;
                    this.RaisePropertyChanged("Cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommercialName {
            get {
                return this.CommercialNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommercialNameField, value) != true)) {
                    this.CommercialNameField = value;
                    this.RaisePropertyChanged("CommercialName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/JCDecaux_API")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableBikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FreeSpaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VLib_Client.VLibSoapService.Position PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalSpaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableBikes {
            get {
                return this.AvailableBikesField;
            }
            set {
                if ((this.AvailableBikesField.Equals(value) != true)) {
                    this.AvailableBikesField = value;
                    this.RaisePropertyChanged("AvailableBikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Banking {
            get {
                return this.BankingField;
            }
            set {
                if ((this.BankingField.Equals(value) != true)) {
                    this.BankingField = value;
                    this.RaisePropertyChanged("Banking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bonus {
            get {
                return this.BonusField;
            }
            set {
                if ((this.BonusField.Equals(value) != true)) {
                    this.BonusField = value;
                    this.RaisePropertyChanged("Bonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FreeSpace {
            get {
                return this.FreeSpaceField;
            }
            set {
                if ((this.FreeSpaceField.Equals(value) != true)) {
                    this.FreeSpaceField = value;
                    this.RaisePropertyChanged("FreeSpace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LastUpdate {
            get {
                return this.LastUpdateField;
            }
            set {
                if ((this.LastUpdateField.Equals(value) != true)) {
                    this.LastUpdateField = value;
                    this.RaisePropertyChanged("LastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VLib_Client.VLibSoapService.Position Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StationName {
            get {
                return this.StationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StationNameField, value) != true)) {
                    this.StationNameField = value;
                    this.RaisePropertyChanged("StationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalSpace {
            get {
                return this.TotalSpaceField;
            }
            set {
                if ((this.TotalSpaceField.Equals(value) != true)) {
                    this.TotalSpaceField = value;
                    this.RaisePropertyChanged("TotalSpace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/JCDecaux_API")]
    [System.SerializableAttribute()]
    public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Step", Namespace="http://schemas.datacontract.org/2004/07/VLib_WSSOAP_API")]
    [System.SerializableAttribute()]
    public partial class Step : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VLib_Client.VLibSoapService.Distance2 distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VLib_Client.VLibSoapService.Duration2 durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VLib_Client.VLibSoapService.EndLocation2 end_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string html_instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maneuverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VLib_Client.VLibSoapService.Polyline polylineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VLib_Client.VLibSoapService.StartLocation2 start_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string travel_modeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VLib_Client.VLibSoapService.Distance2 distance {
            get {
                return this.distanceField;
            }
            set {
                if ((object.ReferenceEquals(this.distanceField, value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VLib_Client.VLibSoapService.Duration2 duration {
            get {
                return this.durationField;
            }
            set {
                if ((object.ReferenceEquals(this.durationField, value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VLib_Client.VLibSoapService.EndLocation2 end_location {
            get {
                return this.end_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.end_locationField, value) != true)) {
                    this.end_locationField = value;
                    this.RaisePropertyChanged("end_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string html_instructions {
            get {
                return this.html_instructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.html_instructionsField, value) != true)) {
                    this.html_instructionsField = value;
                    this.RaisePropertyChanged("html_instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maneuver {
            get {
                return this.maneuverField;
            }
            set {
                if ((object.ReferenceEquals(this.maneuverField, value) != true)) {
                    this.maneuverField = value;
                    this.RaisePropertyChanged("maneuver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VLib_Client.VLibSoapService.Polyline polyline {
            get {
                return this.polylineField;
            }
            set {
                if ((object.ReferenceEquals(this.polylineField, value) != true)) {
                    this.polylineField = value;
                    this.RaisePropertyChanged("polyline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VLib_Client.VLibSoapService.StartLocation2 start_location {
            get {
                return this.start_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.start_locationField, value) != true)) {
                    this.start_locationField = value;
                    this.RaisePropertyChanged("start_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string travel_mode {
            get {
                return this.travel_modeField;
            }
            set {
                if ((object.ReferenceEquals(this.travel_modeField, value) != true)) {
                    this.travel_modeField = value;
                    this.RaisePropertyChanged("travel_mode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distance2", Namespace="http://schemas.datacontract.org/2004/07/VLib_WSSOAP_API")]
    [System.SerializableAttribute()]
    public partial class Distance2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Duration2", Namespace="http://schemas.datacontract.org/2004/07/VLib_WSSOAP_API")]
    [System.SerializableAttribute()]
    public partial class Duration2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndLocation2", Namespace="http://schemas.datacontract.org/2004/07/VLib_WSSOAP_API")]
    [System.SerializableAttribute()]
    public partial class EndLocation2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Polyline", Namespace="http://schemas.datacontract.org/2004/07/VLib_WSSOAP_API")]
    [System.SerializableAttribute()]
    public partial class Polyline : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string points {
            get {
                return this.pointsField;
            }
            set {
                if ((object.ReferenceEquals(this.pointsField, value) != true)) {
                    this.pointsField = value;
                    this.RaisePropertyChanged("points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartLocation2", Namespace="http://schemas.datacontract.org/2004/07/VLib_WSSOAP_API")]
    [System.SerializableAttribute()]
    public partial class StartLocation2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lngField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VLibSoapService.IVLibSoapService")]
    public interface IVLibSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/fullFeed", ReplyAction="http://tempuri.org/IVLibSoapService/fullFeedResponse")]
        bool fullFeed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/fullFeed", ReplyAction="http://tempuri.org/IVLibSoapService/fullFeedResponse")]
        System.Threading.Tasks.Task<bool> fullFeedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getContracts", ReplyAction="http://tempuri.org/IVLibSoapService/getContractsResponse")]
        VLib_Client.VLibSoapService.Contract[] getContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getContracts", ReplyAction="http://tempuri.org/IVLibSoapService/getContractsResponse")]
        System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Contract[]> getContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getStations", ReplyAction="http://tempuri.org/IVLibSoapService/getStationsResponse")]
        VLib_Client.VLibSoapService.Station[] getStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getStations", ReplyAction="http://tempuri.org/IVLibSoapService/getStationsResponse")]
        System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Station[]> getStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getAllStationsIn", ReplyAction="http://tempuri.org/IVLibSoapService/getAllStationsInResponse")]
        VLib_Client.VLibSoapService.Station[] getAllStationsIn(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getAllStationsIn", ReplyAction="http://tempuri.org/IVLibSoapService/getAllStationsInResponse")]
        System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Station[]> getAllStationsInAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getStaticMapImage", ReplyAction="http://tempuri.org/IVLibSoapService/getStaticMapImageResponse")]
        System.Drawing.Bitmap getStaticMapImage(bool isPedestrian, string srcAddress, string destAddres, bool ignoreException);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getStaticMapImage", ReplyAction="http://tempuri.org/IVLibSoapService/getStaticMapImageResponse")]
        System.Threading.Tasks.Task<System.Drawing.Bitmap> getStaticMapImageAsync(bool isPedestrian, string srcAddress, string destAddres, bool ignoreException);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getStationByName", ReplyAction="http://tempuri.org/IVLibSoapService/getStationByNameResponse")]
        VLib_Client.VLibSoapService.Station getStationByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getStationByName", ReplyAction="http://tempuri.org/IVLibSoapService/getStationByNameResponse")]
        System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Station> getStationByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getInstructions", ReplyAction="http://tempuri.org/IVLibSoapService/getInstructionsResponse")]
        VLib_Client.VLibSoapService.Step[] getInstructions(bool isPedestrian, string srcAddress, string destAddres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVLibSoapService/getInstructions", ReplyAction="http://tempuri.org/IVLibSoapService/getInstructionsResponse")]
        System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Step[]> getInstructionsAsync(bool isPedestrian, string srcAddress, string destAddres);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVLibSoapServiceChannel : VLib_Client.VLibSoapService.IVLibSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VLibSoapServiceClient : System.ServiceModel.ClientBase<VLib_Client.VLibSoapService.IVLibSoapService>, VLib_Client.VLibSoapService.IVLibSoapService {
        
        public VLibSoapServiceClient() {
        }
        
        public VLibSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VLibSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VLibSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VLibSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool fullFeed() {
            return base.Channel.fullFeed();
        }
        
        public System.Threading.Tasks.Task<bool> fullFeedAsync() {
            return base.Channel.fullFeedAsync();
        }
        
        public VLib_Client.VLibSoapService.Contract[] getContracts() {
            return base.Channel.getContracts();
        }
        
        public System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Contract[]> getContractsAsync() {
            return base.Channel.getContractsAsync();
        }
        
        public VLib_Client.VLibSoapService.Station[] getStations() {
            return base.Channel.getStations();
        }
        
        public System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Station[]> getStationsAsync() {
            return base.Channel.getStationsAsync();
        }
        
        public VLib_Client.VLibSoapService.Station[] getAllStationsIn(string city) {
            return base.Channel.getAllStationsIn(city);
        }
        
        public System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Station[]> getAllStationsInAsync(string city) {
            return base.Channel.getAllStationsInAsync(city);
        }
        
        public System.Drawing.Bitmap getStaticMapImage(bool isPedestrian, string srcAddress, string destAddres, bool ignoreException) {
            return base.Channel.getStaticMapImage(isPedestrian, srcAddress, destAddres, ignoreException);
        }
        
        public System.Threading.Tasks.Task<System.Drawing.Bitmap> getStaticMapImageAsync(bool isPedestrian, string srcAddress, string destAddres, bool ignoreException) {
            return base.Channel.getStaticMapImageAsync(isPedestrian, srcAddress, destAddres, ignoreException);
        }
        
        public VLib_Client.VLibSoapService.Station getStationByName(string name) {
            return base.Channel.getStationByName(name);
        }
        
        public System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Station> getStationByNameAsync(string name) {
            return base.Channel.getStationByNameAsync(name);
        }
        
        public VLib_Client.VLibSoapService.Step[] getInstructions(bool isPedestrian, string srcAddress, string destAddres) {
            return base.Channel.getInstructions(isPedestrian, srcAddress, destAddres);
        }
        
        public System.Threading.Tasks.Task<VLib_Client.VLibSoapService.Step[]> getInstructionsAsync(bool isPedestrian, string srcAddress, string destAddres) {
            return base.Channel.getInstructionsAsync(isPedestrian, srcAddress, destAddres);
        }
    }
}
